

try:
    print(x)
except:
    print("exception occured")

try:
    print(5/0)
except ZeroDivisionError
    print("exception occured")